language: node_js

node_js:
- stable

dist: trusty

addons:
  apt:
    packages:
    - gcc
    - g++
    - libstdc++6
    - pulseaudio

#TODO Use Xenial https://docs.travis-ci.com/user/gui-and-headless-browsers/#using-services
#dist: xenial
#services:
#  - xvfb
#addons:
#  chrome: stable
#script: xvfb-run --auto-servernum --server-num=1 npm test

cache:
  directories:
  - $HOME/.npm
  - node_modules

before_install:
- export CHROME_BIN=chromium-browser
#- export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
- pulseaudio --start

before_script:
- DEBUG=eslint:cli-engine npm run lint:all

before_deploy:
- npm run build

deploy:
- provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: dist
  on:
    branch: master
- provider: npm
  email: kirill.konshin@gmail.com
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    node: stable
    tags: true
    repo: ringcentral/ringcentral-web-phone
- provider: releases
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  file:
  - dist/ringcentral-web-phone.js
  - dist/ringcentral-web-phone.min.js
  on:
    node: stable
    tags: true
    repo: ringcentral/ringcentral-web-phone

after_success:
- npm run test:coverage
